### ISSUE TITLE
Including a Webpack Config Would Make Things Easier for Newbies

### ISSUE THREAD

**Issue by jean-Phil** [lsycxyj/vue-l-carousel#1]
Hello Light Leung,

I like your implementation very much. Thank you for sharing!

I'm new to Vue.js —and thus to .vue files—. I am having trouble setting my webpack.config file properly.  I tried to build one based on your package.json dependencies, but something isn't right... Would you mind sharing yours? It would make the code more accessible to newbies like myself.

Thank you in advance!

JP

**Comment by jean-Phil** [comment]
__Apologies!__ I didn't really look through, everything, did I ?!

**Comment by lsycxyj** [comment]
It's OK. :)
