### ISSUE TITLE
All items are appearing together. All images are showing only in first slide.

### ISSUE THREAD

**Issue by dmosyash** [lsycxyj/vue-l-carousel#2]

**Comment by lsycxyj** [comment]
Could you give me a demo?

**Comment by lsycxyj** [comment]
This issue will be closed if it couldn't recur.

**Comment by dmosyash** [comment]
I create a new vue app using webpack and just copy pasted the code which is shown in readme file. Installed the component via npm as per told in the document. And I found that all the <p> tags in <carousel-items> were present in first slide only other two were blank.
Do i need to add any specific css for this?

**Comment by dmosyash** [comment]
I haven't publish it any where. If u need exact code i can share my repository with you

**Comment by lsycxyj** [comment]
https://github.com/lsycxyj/vue-l-carousel/blob/master/dist/main.css
You need both js and css to make it work.

**Comment by dmosyash** [comment]
But is it not in component itself?

**Comment by dmosyash** [comment]
My repository link https://github.com/dmosyash/vue_demo.git
Thanks in advance

**Comment by dmosyash** [comment]
Its working after pasting css in the component where i am using the vue-l-carousel component. Thanks
