### ISSUE TITLE
Remove Less dependancy?

### ISSUE THREAD

**Issue by Riaan-ZA** [lsycxyj/vue-l-carousel#4]
Is is possible to remove the dependancy on LESS? The css wont compile on projects that don't use LESS. I'm sure vanilla CSS would work

**Comment by lsycxyj** [comment]
CSS preprocessor can help me organize the code better. You can either use the precompiled one which has pure css, or add LESS config on your project if you want to use the source code of vue-l-carsousel.

**Comment by lsycxyj** [comment]
CSS preprocessor can help me organize the code better. You can either use the precompiled one which has pure css, or add LESS config on your project if you want to use the source code of vue-l-carsousel.

close #4
