### ISSUE TITLE
Issue on Microsoft Surface - carousel touch swiping issue on Edge browser

### ISSUE THREAD

**Issue by pratiksingh05** [lsycxyj/vue-l-carousel#8]
On Surface , carousel not swiping in Edge but it's working in chrome with same functionality.
does anyone knows this is the known issue or bug on edge?

please check and reply asap,Thanks

**Comment by lsycxyj** [comment]
Look [here](https://github.com/MicrosoftEdge/WebAppsDocs/issues/39). It seems to be a bug of edge and I can't find a good solution, please tell me if you find one.
